### ISSUE TITLE
Hide message from "Message Deleted"/"User Timed Out"/"User Banned" events

### ISSUE THREAD

**Issue by rondhi** [izzy/stream-chat#14]
Is it possible to hide a message if said message is deleted, or if the user is timed out/banned? Current solution is to just refresh the browser source if one of those events happens.

**Comment by izzy** [comment]
I thought about it but didn't come across any events emitted for that(see https://wiki.streamer.bot/en/Servers-Clients/WebSocket-Server/Events#twitch ), so the only way would be some Custom Events for the time being, which seems kinda hacky. I think the best way to go forward with this would be to bother the dev to actually include messages about deletion/banning into the websocket, everything else would just make things overly complicated for users who aren't as tech-savvy. :/

**Comment by izzy** [comment]
Opened a feature request at https://ideas.streamer.bot/posts/354/user-ban-timeout-and-message-deleted-in-websocket

**Comment by izzy** [comment]
This is implemented in the latest version 0.1.4 :)

**Comment by xoxfaby** [comment]
Deleted messaged worked for me but timing out did not remove any messages

![](https://faby.dev/images/p0pkBR.png)

**Comment by izzy** [comment]
> Deleted messaged worked for me but timing out did not remove any messages

Do you mind opening a new issue for this? I'm pretty sure this used to work, so it'll need investigation.
