### ISSUE TITLE
Save the settings on the generator page

### ISSUE THREAD

**Issue by izzy** [izzy/stream-chat#23]
I see two options

* via localstorage(when available)
* Load settings via URL

**Comment by lodenrogue** [comment]
You could also consider loading/downloading a settings file. Maybe in JSON.

**Comment by izzy** [comment]
Not a bad idea, but I think we kinda do have a standardised export format already(the URL we give the user) - don't you think that's already a very copy/pasteable format for settings?

Heck, for loading it would probably be relatively easy to just have a text field to paste a URL into, strip the part up until the `?` and load the rest of it into the form, right?

**Comment by izzy** [comment]
Reminder for myself: This, but also a conversion for v0.1.x to v0.2.x before the code for #24 is released.
