### ISSUE TITLE
Some of the customizable fields don't work (at least in my case)

### ISSUE THREAD

**Issue by bogdan-baerov** [izzy/stream-chat#35]
Hello! First of all, I wanted to say that I love this repo a lot! Thank you so much for all the work, it is awesome.

For a better understanding of what I want to do to use both the chat bubble and the vertical chat from the same chat.html, but with slightly different settings, and I want to keep it as simple as possible, with no badges, timestamps, pronouns or other things, just the username, text and emotes and maybe announcements to be displayed differently (which I saw it was added to the code already).

Now, getting to the issue at hand, the issues I encountered are:
- pronouns appear whatever I do;
- the username color remains the same (Twitch username color), even if I have set up the text_color in the link and the other text color variables in the browser source link;
- also this is more of a nice-to-have thing, but in case the user selects vertical/horizontal vs bubble, it would be nice to have a different set of settings for each, for example, I'd want the username to be bigger on the bubble chat and smaller on the vertical chat.

I can do those changes directly in the CSS part of the HTML myself, but that would be very ok since the repo is getting updated and I'll have to adapt what I wrote every time it gets an update.

**Comment by izzy** [comment]
1 => In terms of the FFZ emotes, I just looked into it and was able to reproduce it. It seems to be a bug in SB. They come back with a duplicated `https:` which obviously won't work:

![image](https://user-images.githubusercontent.com/360964/227791020-4ecadc46-0fcf-4dd5-8989-6b05506f17f2.png)

I'll upload a preliminary patch with a workaround later. I'll update this one as soon as that's done so you can test if you'd like :)

5 => For more options for the bubble it'd be great if you could open a different issue with a list of options you'd like to see, just so I can track that as a different enhancement.

**Comment by izzy** [comment]
There's a new release of the chat which adds a workaround for malformed emote URLs for FFZ emotes coming from SB. You can download the pre-release at: https://github.com/izzy/stream-chat/releases/tag/v0.2.3
